#!/usr/bin/env bash
#
# Create (or refresh) the pinned Python reference environment and record exactly
# what got resolved. The resolved-versions file is what makes a golden run
# auditable later — without it, "the goldens changed" is unanswerable.
#
# Usage:
#   bench/setup_reference_env.sh            # create if missing, then verify
#   bench/setup_reference_env.sh --force    # tear down and recreate
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_NAME="${ISONFORM_REF_ENV:-isonform-ref}"
ENV_FILE="$REPO_ROOT/bench/env/reference.yml"

FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

if ! command -v conda >/dev/null 2>&1; then
  echo "error: conda not found on PATH." >&2
  echo "Install miniforge (https://github.com/conda-forge/miniforge) and re-run." >&2
  exit 1
fi

# mamba resolves this environment far faster than classic conda; use it if present.
SOLVER="conda"
command -v mamba >/dev/null 2>&1 && SOLVER="mamba"

env_exists() { conda env list | awk '{print $1}' | grep -qx "$ENV_NAME"; }

if [[ $FORCE -eq 1 ]] && env_exists; then
  echo "==> removing existing env '$ENV_NAME'"
  conda env remove -n "$ENV_NAME" -y
fi

if env_exists; then
  echo "==> env '$ENV_NAME' already exists (use --force to recreate)"
else
  echo "==> creating env '$ENV_NAME' with $SOLVER"
  "$SOLVER" env create -n "$ENV_NAME" -f "$ENV_FILE" -y
fi

# Use the environment's interpreter directly rather than `conda run`: conda run
# does not forward stdin, which silently swallows heredoc-fed scripts.
PREFIX="$(conda env list | awk -v n="$ENV_NAME" '$1==n {print $NF; exit}')"
if [[ -z "$PREFIX" || ! -x "$PREFIX/bin/python" ]]; then
  echo "error: could not locate python for env '$ENV_NAME'" >&2
  exit 1
fi
PY_BIN="$PREFIX/bin/python"
export PATH="$PREFIX/bin:$PATH"

# isONform is *not* pip-installed here. Its two entry points are plain scripts
# at the repository root that do `from modules import ...`, so they only import
# when the repository root is the working directory (or on PYTHONPATH). Every
# bench script invokes them that way; installing would add a second, divergent
# copy of the modules under site-packages.

echo "==> verifying"
"$PY_BIN" - <<'PY'
import importlib, shutil, sys

# Reference dependencies: without these isONform cannot run at all.
missing = []
for mod in ("networkx", "parasail"):
    try:
        importlib.import_module(mod)
    except Exception as exc:  # noqa: BLE001 - want the reason, whatever it is
        missing.append(f"{mod}: {exc}")
if shutil.which("spoa") is None:
    missing.append("spoa: binary not found on PATH")

if missing:
    print("FAILED (reference dependencies):", file=sys.stderr)
    for m in missing:
        print("  -", m, file=sys.stderr)
    sys.exit(1)

# Evaluation dependencies: bench/accuracy_isoforms*.py need these, nothing on
# any isONform code path does. A warning, not a failure --- the equivalence
# harness and the determinism check work without them.
soft = []
try:
    importlib.import_module("edlib")
except Exception as exc:  # noqa: BLE001
    soft.append(f"edlib: {exc}  (needed by bench/accuracy_isoforms.py)")
if shutil.which("minimap2") is None:
    soft.append("minimap2: not on PATH  (needed by bench/accuracy_isoforms_genome.py)")

print("ok")
for s in soft:
    print("  warning:", s, file=sys.stderr)
PY

echo "==> checking the repository's own entry points import"
( cd "$REPO_ROOT" && "$PY_BIN" -c "
import runpy, sys
sys.argv = ['main', '--help']
try:
    runpy.run_path('main', run_name='__main__')
except SystemExit:
    pass
" >/dev/null ) && echo "main --help ok"

PLATFORM="$("$PY_BIN" -c 'import sysconfig; print(sysconfig.get_platform())')"
RESOLVED="$REPO_ROOT/bench/env/resolved-${PLATFORM}.txt"

echo "==> recording resolved versions to bench/env/resolved-${PLATFORM}.txt"
{
  echo "# Resolved reference environment. Generated by bench/setup_reference_env.sh."
  echo "# Goldens recorded under a different set of versions are not comparable."
  echo "platform: $PLATFORM"
  echo "env_name: $ENV_NAME"
  echo
  echo "## key versions"
  "$PY_BIN" - <<'PY'
import subprocess, sys
import networkx, parasail

def tool(cmd):
    try:
        v = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        return (v.stdout or v.stderr).strip().splitlines()[0]
    except Exception as exc:  # noqa: BLE001
        return f"UNKNOWN ({exc})"

print("# reference")
print(f"python: {sys.version.split()[0]}")
print(f"networkx: {networkx.__version__}")
print(f"parasail: {parasail.__version__}")
# spoa writes its version to stdout and exits 0.
print(f"spoa: {tool(['spoa', '--version'])}")

# Evaluation only. Recorded because an accuracy number is not auditable without
# knowing what produced it, even though these cannot affect reference output.
print("# evaluation only")
# edlib exposes no __version__, so read the installed distribution's metadata.
# "present, version unknown" is not an audit trail.
try:
    import importlib.metadata as md
    import edlib  # noqa: F401  -- confirm it imports, not just that it is installed
    print(f"edlib: {md.version('edlib')}")
except Exception as exc:  # noqa: BLE001
    print(f"edlib: ABSENT or unreadable ({exc})")
print(f"minimap2: {tool(['minimap2', '--version'])}")
PY
  echo
  echo "## full conda list"
  conda list -n "$ENV_NAME"
} > "$RESOLVED"

echo
sed -n '1,20p' "$RESOLVED"
echo
echo "Reference environment ready. Activate with:  conda activate $ENV_NAME"
